server:
  port: 8100
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: client
      clientSecret: password
    resource:
      userInfoUri: http://localhost:8090/auth/user/me