server:
  port: 8100
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: client
      clientSecret: password
    resource:
      # 172.21.0.1 si le service tourne dans un container localhost sinon
      userInfoUri: http://172.21.0.1:8090/auth/user/me