server:
  port: 8100
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: client
      clientSecret: password
    resource:
      # 172.21.0.1 ou authorization-service si le service tourne dans un container ou k8s,  localhost sinon
      userInfoUri: http://authorization-service:8090/auth/user/me