server:
  port: 8100
spring:
  application:
    name: utilisateur
security:
  oauth2:
    client:
      client-id: 0oakz6w946XN0GAcj356
      client-secret: -SmoZw_w10UAZZQESfoZH_2N1oYCzShpLzQXkqWG
    resource:
      token-info-uri: https://dev-847930.okta.com/oauth2/default/v1/introspect